Update README
The gem should not be required by Bundler for several reasons:
* We are requiring it manually in spec_helper.rb
* Because Flowaker depends on rspec already being required, if Bundle
  requires it first, then the test environment will not load with the
  following error:
  undefined method `configuration' for RSpec:Module (NoMethodError)'